{ lib, config, ... }:
with lib;
let
  cfg = config.services.containers.newt;
in
{
  options.services.containers.newt = {
    enable = mkEnableOption "Enable newt the pangolin reverse proxy";
    version = mkOption {
      type = types.str;
      default = "v1.3.0";
    };
    dataLocation = mkOption {
      type = types.str;
      default = "${config.users.users.osmo.home}/newt";
    };
    options = {
    };
  };

  config = mkIf cfg.enable {
    virtualisation.oci-containers.containers."newt" = {
      image = "fosrl/newt:${cfg.version}";
      environment = {
        "DOCKER_SOCKET" = "${config.hostSpec.ip}:2375";
      };
      volumes = [ "/etc/resolv.conf:/etc/resolv.conf:ro" ];
      environmentFiles = [ "${cfg.dataLocation}/.env" ];
      log-driver = "journald";
      extraOptions = [
        "--network-alias=newt"
      ];
    };
    systemd.services."podman-newt" = {
      serviceConfig = {
        Restart = lib.mkOverride 90 "always";
      };
      partOf = [
        "podman-compose-newt-root.target"
      ];
      wantedBy = [
        "podman-compose-newt-root.target"
      ];
    };

    # Root service
    # When started, this will automatically create all resources and start
    # the containers. When stopped, this will teardown all resources.
    systemd.targets."podman-compose-newt-root" = {
      unitConfig = {
        Description = "Root target generated by compose2nix.";
      };
      wantedBy = [ "multi-user.target" ];
    };

    networking.firewall.allowedTCPPorts = [
    ];
    systemd.tmpfiles.rules = [
      "d ${cfg.dataLocation} 0770 osmo users - -"
      "f ${cfg.dataLocation}/.env 0770 osmo users - -"
    ];
  };
}
