[config]
".secrets/klusteri-0/ssh.pub" = ["age1mha92vta5u0qsazst32lmcje5qhvmzcwm5tf6ws0usy4s7fkyezqp0f9fa"]
".secrets/testeri/git.pub" = ["age1mha92vta5u0qsazst32lmcje5qhvmzcwm5tf6ws0usy4s7fkyezqp0f9fa"]
".secrets/serveri/git.pub" = ["age1mha92vta5u0qsazst32lmcje5qhvmzcwm5tf6ws0usy4s7fkyezqp0f9fa"]
".secrets/klusteri-1/ssh.pub" = ["age1mha92vta5u0qsazst32lmcje5qhvmzcwm5tf6ws0usy4s7fkyezqp0f9fa"]
".secrets/password.nix" = ["age1mha92vta5u0qsazst32lmcje5qhvmzcwm5tf6ws0usy4s7fkyezqp0f9fa"]
".secrets/klusteri-0/git.pub" = ["age1mha92vta5u0qsazst32lmcje5qhvmzcwm5tf6ws0usy4s7fkyezqp0f9fa"]
".secrets/serveri/ssh.pub" = ["age1mha92vta5u0qsazst32lmcje5qhvmzcwm5tf6ws0usy4s7fkyezqp0f9fa"]
".secrets/testeri/ssh.pub" = ["age1mha92vta5u0qsazst32lmcje5qhvmzcwm5tf6ws0usy4s7fkyezqp0f9fa"]
".secrets/klusteri-1/git.pub" = ["age1mha92vta5u0qsazst32lmcje5qhvmzcwm5tf6ws0usy4s7fkyezqp0f9fa"]
